### ISSUE TITLE
With Image Info Dialog showing, errors for key up/key down events

### ISSUE THREAD

**Issue by itsayellow** [itsayellow/marcam#116]
```
UnboundLocalError: local variable 'return_frame' referenced before assignment
Traceback (most recent call last):
  File "marcam/marcam.py", line 2224, in on_key_down
    self.file_windows.active_frame().on_key_down(evt)
  File "/Users/mclapp/git/marcam/marcam/common.py", line 46, in func_wrapper
    return_vals = func(*args, **kwargs)
  File "marcam/marcam.py", line 2014, in active_frame
    return return_frame
UnboundLocalError: local variable 'return_frame' referenced before assignment
Traceback (most recent call last):
  File "marcam/marcam.py", line 2227, in on_key_up
    self.file_windows.active_frame().on_key_up(evt)
  File "/Users/mclapp/git/marcam/marcam/common.py", line 46, in func_wrapper
    return_vals = func(*args, **kwargs)
  File "marcam/marcam.py", line 2014, in active_frame
    return return_frame
UnboundLocalError: local variable 'return_frame' referenced before assignment
```

**Comment by itsayellow** [comment]
This occurred in Windows, Mac doesn't seem to process key events with a Modal Dialog showing.

Successfully return None from active_frame() if no frame is active, and handle None return in on_key_{up,down}.

Fixed in commit c2ec387
