### ISSUE TITLE
Need to handle running threads in ImageCache if parent window is destroyed.

### ISSUE THREAD

**Issue by itsayellow** [itsayellow/marcam#145]
If an ImageScrolledCanvas in a ImageFrame is closed before the threads in ImageCache are finished, they will try to send an event to a non-existent window, causing an error.

Also, probably there is some trouble with ImageFrame deleting the cache directory while ImageCache is still accessing files there.

```
2018-09-18 22:58:41,687:image_scrolled_canvas:INFO:
    <--FXNThread-2.2: image_scrolled_canvas.ImageCache._create_cache_file_thread
       RETURNS: None
2018-09-18 22:58:41,706:marcam_extra:ERROR:
    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
      File "/Users/mclapp/git/marcam/marcam/common.py", line 103, in func_wrapper
        return_vals = func(*args, **kwargs)
      File "/Users/mclapp/git/marcam/marcam/longtask.py", line 105, in long_task_thread
        wx.PostEvent(self.win_parent, self.myLongTaskDoneEvent())
    RuntimeError: wrapped C/C++ object of type ImageScrolledCanvasMarks has been deleted
    
```

**Comment by itsayellow** [comment]
Options:
1. When closing ImageFrame, just immediately Hide it, the wait for all active threads to finish before destroying it
1. Sub-Class threading.Thread and add a "stop" Event. Check for stop event before sending wx Event to window (if stop event found, abort and don't send wx Event).  (https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python)  Could use another thread that waits on join'ed active threads to delete Cache directory.  
1. Use multiprocessing, and just kill process when window is destroyed

**Comment by itsayellow** [comment]
Maybe we should keep track of ImageCache in ImageFrame, so that we can use EVT_CLOSE handler to gracefully shut it down.  We can pass the ImageCache object to ImageScrolledCanvasMarks.
