### ISSUE TITLE
Harmonize ImageWindow.on_evt_close() and ImageWindow.on_close()

### ISSUE THREAD

**Issue by itsayellow** [itsayellow/marcam#80]
We should need to do the same things for both.

Also, on Mac we don't want to quit the app on closing the last frame, but instead to hide it.

**Comment by itsayellow** [comment]
Allowing on_evt_close to close window without deleting frame in wxpython may cause the following error:
```
Traceback (most recent call last):
  File "/Users/mclapp/git/marcam/marcam/common.py", line 38, in func_wrapper
    return func(*args, **kwargs)
  File "marcam/marcam.py", line 771, in on_quit
    self.parent.quit_app()
  File "/Users/mclapp/git/marcam/marcam/common.py", line 38, in func_wrapper
    return func(*args, **kwargs)
  File "marcam/marcam.py", line 1595, in quit_app
    frame_closed = self.close_frame(frame.GetId(), force_close=True)
RuntimeError: wrapped C/C++ object of type ImageWindow has been deleted
```

**Comment by itsayellow** [comment]
Also, need to prevent closing last window, just hide instead.
